language: swift
os: osx
osx_image: xcode10.3

branches:
  only:
    - test-travis
    - /^\d+\.\d+\.\d+$/

stages:
  - name: lint
    if: NOT branch =~ ^\d+\.\d+\.\d+$
  - name: carthage
    if: branch = test-travis OR branch =~ /^\d+\.\d+\.\d+$/
  - name: test
    if: branch = test-travis OR branch =~ /^\d+\.\d+\.\d+$/
  # - name: deploy
  #   if: branch =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    # - &pod
    #   stage: lint
    #   install: gem install cocoapods -v '~> 1.7.0'
    #   script: pod lib lint --fail-fast --allow-warnings

    - &carthage
      stage: carthage
      name: iOS
      env: PLATFORM=ios
      install: pod install && carthage update  --platform $PLATFORM
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      before_script: |
        sed -i '' "s/SWIFT_TREAT_WARNINGS_AS_ERRORS = NO;/SWIFT_TREAT_WARNINGS_AS_ERRORS = YES;/" *.xcodeproj/project.pbxproj
        sed -i '' "s/GCC_TREAT_WARNINGS_AS_ERRORS = NO;/GCC_TREAT_WARNINGS_AS_ERRORS = YES;/" *.xcodeproj/project.pbxproj
      script: carthage build --no-skip-current --configuration Release --platform $PLATFORM
    # - <<: *carthage
    #   name: tvOS
    #   env: PLATFORM=tvos
    # - <<: *carthage
    #   name: macOS
    #   env: PLATFORM=macos
    # - name: "`pod trunk push`"
    #   stage: deploy
    #   install: gem install cocoapods -v '~> 1.7.0'
    #   script: |
    #     set -exo pipefail
    #     pod trunk push --verbose --allow-warnings | tee pod.log | ruby -e 'ARGF.each{ print "." }'
    #   after_failure: cat pod.log | grep error
