//
//  Constants.swift
//  YouboraConfigUtils
//
//  Created by nice on 03/10/2019.
//  Copyright © 2019 NPAW. All rights reserved.
//

import Foundation

@objc public enum OptionType : Int {
    case String = 0
    case Bool = 1
    case Number = 2
    case Unknown = 3
}


public struct Option {
    let name: String
    let type: OptionType
}

struct Constants {
    static let youborasettings = "youborasettings"
    static let settingsNavTitle = "Youbora Settings"
    static let defaultCellId = "defaultCellId"
    static let boolCellId = "cellBoolIdentifier"
    static let stringCellId = "cellStringIdentifier"
    static let numberCellId = "cellNumberIdentifier"
    static let unknownCellId = "cellUnknownIdentifier"
}

extension Constants {
    static let options: [Option] = [
        Option(name: "enabled", type: .Bool),
        Option(name: "httpSecure", type: .Bool),
        Option(name: "host", type: .String),
        Option(name: "accountCode", type: .String),
        Option(name: "username", type: .String),
        Option(name: "userType", type: .String),
        Option(name: "userEmail", type: .String),
        Option(name: "parseHls", type: .Bool),
        Option(name: "parseLocationHeader", type: .Bool),
        Option(name: "parseCdnNameHeader", type: .String),
        Option(name: "parseCdnNode", type: .Bool),
        Option(name: "parseCdnNodeList", type: .Unknown),
        Option(name: "experimentIds", type: .Unknown),
        Option(name: "networkIP", type: .String),
        Option(name: "networkIsp", type: .String),
        Option(name: "networkConnectionType", type: .String),
        Option(name: "userObfuscateIp", type: .Unknown),
        Option(name: "deviceCode", type: .String),
        Option(name: "forceInit", type: .Bool),
        Option(name: "deviceModel", type: .String),
        Option(name: "deviceBrand", type: .String),
        Option(name: "deviceType", type: .String),
        Option(name: "deviceName", type: .String),
        Option(name: "deviceOsName", type: .String),
        Option(name: "deviceOsVersion", type: .String),
        Option(name: "deviceIsAnonymous", type: .Bool),
        Option(name: "contentResource", type: .String),
        Option(name: "contentIsLive", type: .Unknown),
        Option(name: "contentTitle", type: .String),
        Option(name: "program", type: .String),
        Option(name: "contentDuration", type: .Number),
        Option(name: "contentTransactionCode", type: .String),
        Option(name: "contentBitrate", type: .Number),
        Option(name: "contentStreamingProtocol", type: .String),
        Option(name: "contentThroughput", type: .Number),
        Option(name: "contentRendition", type: .String),
        Option(name: "contentCdn", type: .String),
        Option(name: "contentFps", type: .Number),
        Option(name: "contentMetadata", type: .Unknown),
        Option(name: "contentMetrics", type: .Unknown),
        Option(name: "sessionMetrics", type: .Unknown),
        Option(name: "contentIsLiveNoSeek", type: .Bool),
        Option(name: "contentPackage", type: .String),
        Option(name: "contentSaga", type: .String),
        Option(name: "contentTvShow", type: .String),
        Option(name: "contentSeason", type: .String),
        Option(name: "contentEpisodeTitle", type: .String),
        Option(name: "contentChannel", type: .String),
        Option(name: "contentId", type: .String),
        Option(name: "contentImdbId", type: .String),
        Option(name: "contentGracenoteId", type: .String),
        Option(name: "contentType", type: .String),
        Option(name: "contentGenre", type: .String),
        Option(name: "contentLanguage", type: .String),
        Option(name: "contentSubtitles", type: .String),
        Option(name: "contentContractedResolution", type: .String),
        Option(name: "contentCost", type: .String),
        Option(name: "contentPrice", type: .String),
        Option(name: "contentPlaybackType", type: .String),
        Option(name: "contentDrm", type: .String),
        Option(name: "contentEncodingVideoCodec", type: .String),
        Option(name: "contentEncodingAudioCodec", type: .String),
        Option(name: "contentEncodingCodecSettings", type: .Unknown),
        Option(name: "contentEncodingCodecProfile", type: .String),
        Option(name: "contentEncodingContainerFormat", type: .String),
        Option(name: "adMetadata", type: .Unknown),
        Option(name: "adsAfterStop", type: .Number),
        Option(name: "adCampaign", type: .String),
        Option(name: "adTitle", type: .String),
        Option(name: "adResource", type: .String),
        Option(name: "adGivenBreaks", type: .Number),
        Option(name: "adExpectedBreaks", type: .Number),
        Option(name: "adExpectedPattern", type: .Unknown),
        Option(name: "adBreaksTime", type: .Unknown),
        Option(name: "adGivenAds", type: .Number),
        Option(name: "adCreativeId", type: .String),
        Option(name: "adProvider", type: .String),
        Option(name: "autoDetectBackground", type: .Bool),
        Option(name: "offline", type: .Bool),
        Option(name: "anonymousUser", type: .String),
        Option(name: "isInfinity", type: .Bool),
        Option(name: "smartswitchConfigCode", type: .String),
        Option(name: "smartswitchGroupCode", type: .String),
        Option(name: "smartswitchContractCode", type: .String),
        //Deprecated
//        Option(name: "extraparam1", type: .String),
//        Option(name: "extraparam2", type: .String),
//        Option(name: "extraparam3", type: .String),
//        Option(name: "extraparam4", type: .String),
//        Option(name: "extraparam5", type: .String),
//        Option(name: "extraparam6", type: .String),
//        Option(name: "extraparam7", type: .String),
//        Option(name: "extraparam8", type: .String),
//        Option(name: "extraparam9", type: .String),
//        Option(name: "extraparam10", type: .String),
//        Option(name: "extraparam11", type: .String),
//        Option(name: "extraparam12", type: .String),
//        Option(name: "extraparam13", type: .String),
//        Option(name: "extraparam14", type: .String),
//        Option(name: "extraparam15", type: .String),
//        Option(name: "extraparam16", type: .String),
//        Option(name: "extraparam17", type: .String),
//        Option(name: "extraparam18", type: .String),
//        Option(name: "extraparam19", type: .String),
//        Option(name: "extraparam20", type: .String),
//        Option(name: "customDimension1", type: .String),
//        Option(name: "customDimension2", type: .String),
//        Option(name: "customDimension3", type: .String),
//        Option(name: "customDimension4", type: .String),
//        Option(name: "customDimension5", type: .String),
//        Option(name: "customDimension6", type: .String),
//        Option(name: "customDimension7", type: .String),
//        Option(name: "customDimension8", type: .String),
//        Option(name: "customDimension9", type: .String),
//        Option(name: "customDimension10", type: .String),
//        Option(name: "customDimension11", type: .String),
//        Option(name: "customDimension12", type: .String),
//        Option(name: "customDimension13", type: .String),
//        Option(name: "customDimension14", type: .String),
//        Option(name: "customDimension15", type: .String),
//        Option(name: "customDimension16", type: .String),
//        Option(name: "customDimension17", type: .String),
//        Option(name: "customDimension18", type: .String),
//        Option(name: "customDimension19", type: .String),
//        Option(name: "customDimension20", type: .String),
//        Option(name: "adExtraparam1", type: .String),
//        Option(name: "adExtraparam2", type: .String),
//        Option(name: "adExtraparam3", type: .String),
//        Option(name: "adExtraparam4", type: .String),
//        Option(name: "adExtraparam5", type: .String),
//        Option(name: "adExtraparam6", type: .String),
//        Option(name: "adExtraparam7", type: .String),
//        Option(name: "adExtraparam8", type: .String),
//        Option(name: "adExtraparam9", type: .String),
//        Option(name: "adExtraparam10", type: .String),
        Option(name: "contentCustomDimension1", type: .String),
        Option(name: "contentCustomDimension2", type: .String),
        Option(name: "contentCustomDimension3", type: .String),
        Option(name: "contentCustomDimension4", type: .String),
        Option(name: "contentCustomDimension5", type: .String),
        Option(name: "contentCustomDimension6", type: .String),
        Option(name: "contentCustomDimension7", type: .String),
        Option(name: "contentCustomDimension8", type: .String),
        Option(name: "contentCustomDimension9", type: .String),
        Option(name: "contentCustomDimension10", type: .String),
        Option(name: "contentCustomDimension11", type: .String),
        Option(name: "contentCustomDimension12", type: .String),
        Option(name: "contentCustomDimension13", type: .String),
        Option(name: "contentCustomDimension14", type: .String),
        Option(name: "contentCustomDimension15", type: .String),
        Option(name: "contentCustomDimension16", type: .String),
        Option(name: "contentCustomDimension17", type: .String),
        Option(name: "contentCustomDimension18", type: .String),
        Option(name: "contentCustomDimension19", type: .String),
        Option(name: "contentCustomDimension20", type: .String),
        Option(name: "adCustomDimension1", type: .String),
        Option(name: "adCustomDimension2", type: .String),
        Option(name: "adCustomDimension3", type: .String),
        Option(name: "adCustomDimension4", type: .String),
        Option(name: "adCustomDimension5", type: .String),
        Option(name: "adCustomDimension6", type: .String),
        Option(name: "adCustomDimension7", type: .String),
        Option(name: "adCustomDimension8", type: .String),
        Option(name: "adCustomDimension9", type: .String),
        Option(name: "adCustomDimension10", type: .String),
        Option(name: "appName", type: .String),
        Option(name: "appReleaseVersion", type: .String),
        Option(name: "waitForMetadata", type: .Bool),
        Option(name: "pendingMetadata", type: .Unknown),
    ]
}
